version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: viewperfect
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'cinemasystem'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
